### ISSUE TITLE
Use buildutil.OverlayContext?

### ISSUE THREAD

**Issue by dominikh** [zmb3/gogetdoc#12]
The code for handling `-modified` archives and the overlay context now exists in golang.org/x/tools/go/buildutil – the question is whether you want to use that, or keep using the version we have in gogetdoc. Using buildutil would mean less code for us to manage, but if people already have an old copy of it checked out, and don't use `go get -u` to install gogetdoc, they'll get build failures.

Up to you. I'll happily send a PR if you decide to use buildutil.

**Comment by zmb3** [comment]
Let's go ahead and use the code from `x/tools`.  I don't mind supporting the occasional issue that springs up related to outdated tools.  I'll even add a note to the readme.
