### ISSUE TITLE
c.Val().ExactString undefined

### ISSUE THREAD

**Issue by holwech** [zmb3/gogetdoc#15]
This could be an issue on my side, but I got an error when calling [vim-go's](https://github.com/fatih/vim-go) `:GoInstallBinaries`.

```
../../zmb3/gogetdoc/ident.go:142: c.Val().ExactString undefined (type constant.Value has no field or method ExactString)
```

**Comment by zmb3** [comment]
Can you check what version of Go you're running?  `gogetdoc` requires 1.6 or later to build.

**Comment by BetaBugish** [comment]
I had the same issue earlier, I was closed the draft issue I had written before I realized I was running 1.5

**Comment by holwech** [comment]
That seems to fix it, thanks for the response!
