### ISSUE TITLE
undefined buildutil.*

### ISSUE THREAD

**Issue by zeroZshadow** [zmb3/gogetdoc#18]
Just ran `go get -u github.com/zmb3/gogetdoc` and this gives me a build error.

```
github.com\zmb3\gogetdoc\main.go:77: undefined: buildutil.ParseOverlayArchive
github.com\zmb3\gogetdoc\main.go:81: undefined: buildutil.OverlayContext
```
My go version is 1.6.2 windows/amd64

**Comment by zmb3** [comment]
This error indicates that your golang.org/x/tools repo is out of date.

go get -u should have updated this for you.  Are you sure you didn't forget the -u option?

**Comment by zeroZshadow** [comment]
It seems that for some reason it had golang.org/x/tools as a git repo on the 1.6 stable branch. Switching to master has resolved the issue!
