### ISSUE TITLE
Enhance output format

### ISSUE THREAD

**Issue by zmb3** [zmb3/gogetdoc#2]
Add support for multiple output formats.  For example, consider the following output types:
- HTML
- JSON
- Go template language

This would allow editors to do fancy things like display the title in a different size, use fixed-width font for argument names, etc.

**Comment by ingshtrom** [comment]
It would be _really_ cool if there was a link in there so you could go straight to the in depth documentation on godoc.org :)

**Comment by zmb3** [comment]
Added JSON output with c852ac5702cea027e0ade3e799a8e2380c506582
