### ISSUE TITLE
Any chance of turning this cmd into an importable lib pkg?

### ISSUE THREAD

**Issue by metaleap** [zmb3/gogetdoc#22]
I can do a PR if you're open to the idea. Which would be: renaming `package main` to `package gogetdoc`, turning the current `func main()` into an exported `func Main()` to be then called from a newly added `package main` cmd importing the above..

Not crucial, just would be neat! I prefer libs over external cmd's for stuff like this as it needs to be installed separately by the user (or added to deployment workload/complexity) and there's no 100% version guarantee like there is with static-linked-import of tool-as-a-lib  =)

**Comment by zmb3** [comment]
Not opposed to the idea but I don't understand the use case. gogetdoc is a program intended to be run by editors. Making it a lib would only be of value to editors written in Go, of which there aren't many. Am I missing something?

**Comment by metaleap** [comment]
Crazy me decided to write a multi-editor-multi-language "ide" backend (in Go) as editors come and go every few years 😁 seeing as I already invoke numerous commands anyway, it's not all that crucial. Although, it could be beneficial if it does expensive startup work that could be retained for subsequent calls! Hrm I'll close this question-non-issue for now and may get back to you with a PR if I do decide to take the time to try this out as a lib later on =)

**Comment by zmb3** [comment]
Sounds a lot like[ language server](https://github.com/sourcegraph/go-langserver).

PS. I'm a maintainer of[ go-plus ](https://github.com/joefitzgerald/go-plus) for Atom, so I suppose I may be one of those random scripters you speak about 😛

**Comment by metaleap** [comment]
> Sounds a lot like go-langserver

Yeah but I'll just easily keep plugging in new languages and/or editors as I change into and out of them over the years, as one is wont to do (today's hot choice is tomorrow's stale sub-optimal abandon-or-legacyware..)

go-plus looks very neat indeed for the Atom crowd! Good reference to fall back on, should I run into quirks/issues with any go*foo* command invocations =)
