### ISSUE TITLE
feature request: return package name with symbol information

### ISSUE THREAD

**Issue by sparrc** [zmb3/gogetdoc#27]
I am using VS Code, which uses gogetdoc to get symbol hover/mouseover information.

Since gogetdoc does not return package information with the symbol information (as I understand it), VS Code is not able to display the package name of the symbol (see https://github.com/Microsoft/vscode-go/issues/1085)

Would it be possible for gogetdoc to return the package name with each symbol?

**Comment by zmb3** [comment]
gogetdoc does return the package of the symbol when invoked with the `-json` flag.  It's in the `import` field.  For example:

```
{
  "name": "RuneCountInString",
  "import":  "unicode/utf8",
  "decl": "func RuneCountInString(s string) (n int)",
  "doc": "RuneCountInString is like RuneCount but its input is a string.\n",
  "pos": "/usr/local/Cellar/go/1.7/libexec/src/unicode/utf8/utf8.go:409:6"
}
```

**Comment by sparrc** [comment]
I see, that's helpful but it's not _exactly_ the package name. In this example the package name is just `utf8`. In this case it happens to be the final element of the import path but that is not necessarily always the case.
