### ISSUE TITLE
make a tag for Go 1.5 by setting tag

### ISSUE THREAD

**Issue by dlintw** [zmb3/gogetdoc#28]
```
$ go get github.com/zmb3/gogetdoc
# github.com/zmb3/gogetdoc
./ident.go:142: c.Val().ExactString undefined (type constant.Value has no field or method ExactString)
```

Is it possible to set a tag to older version then it is workable for Go 1.5.1( Centos 6 newest Go version)
eg.  4ecb996f211c3c2bdfa1fc1cac2cdd9be30300b2

**Comment by zmb3** [comment]
No, the type checker that powers all of this wasn't added to the standard library until 1.6.

Note that you only need Go 1.6 to build the tool, not to run it. You can install a newer version of Go or build the tool on a machine with a newer version and then copy the binary to your CentOS machine.
