### ISSUE TITLE
If `-json` output is requested, might be good to always force all gogetdoc outputs into JSON

### ISSUE THREAD

**Issue by metaleap** [zmb3/gogetdoc#30]
To illustrate what I mean, consider that one currently has to hard-code special non-JSON-output cases as one accidentally runs into them, e.g.:

https://github.com/metaleap/go-util/commit/c82fa0d0f814f48273d33185c813aaade77f3ca5#diff-3482478175d30d20e81d5d6ff7611d61R253

(One will note in the above that the special non-JSON-output cases do indeed occur not over stderr but stdout.)

Nothing urgent of course.. just noting it down here for the record, in case any contributor (perhaps even me in the future) feels at leisure to tweak the program's output behaviors with `-json` on  =)

**Comment by zmb3** [comment]
I hear what you’re saying, but the JSON flag is for getting structured output. I disagree with having it alter stderr. 

One does not need to hard code special error cases - they should simply look at the process exit code and only attempt to parse JSON if the exit code was 0. If gogetdoc does not return nonzero exit on error then that is a bug we will fix.

**Comment by metaleap** [comment]
>  I disagree with having it alter stderr.

Not what I'm saying, stderr would be fine but I got these non-json outputs (linked above) on stdout as far as I could tell.. unless my pipes are all messed up. But it's true that I don't handle exit code, only stdout/stderr --- will go back into this tonight and report here or close the issue then

**Comment by zmb3** [comment]
Moved the error output to stderr with b4c1dcb095da28d1d54e10184a3eddd9b0122f89.  Does this work better for you?

**Comment by metaleap** [comment]
Yes, now I could remove the special-case handling and the existing stderr-handling triggers. Cleaner for sure, and also one less trap for other future `-json` users --- cheers  =)
