### ISSUE TITLE
Gogetdock doesn't work if source file specified build tags.

### ISSUE THREAD

**Issue by vagruchi** [zmb3/gogetdoc#31]
Before submitting an issue, please make sure:
- [x] You're running Go 1.6 or later - later
- [x] You've tried installing with `go get -u` to update dependencies - yes

I write tests with build tag. And i tried see documentation in this file. I recieve followed error:
gogetdoc: couldn't find /.../file_test.go in program.

I understand where it come from. And is it possible to fix it?

**Comment by zmb3** [comment]
gogetdoc does support build tags, but it’s up to your editor to specify the correct tags. What editor are you using?

**Comment by purpuregecko** [comment]
Atom with go-plus plugin.
