### ISSUE TITLE
Support Go modules

### ISSUE THREAD

**Issue by nicpottier** [zmb3/gogetdoc#36]
As vgo has been accepted, would be great to get `gogetdoc` updated to find the right docs based on the source location under `$GOPATH/src/v`. 

See https://github.com/Microsoft/vscode-go/issues/1532#issuecomment-392173256

**Comment by zmb3** [comment]
Totally!  I suspect that `go/types` (the package upon which this tool is built) will actually take care of that for us once `vgo` becomes part of the toolchain.

**Comment by zmb3** [comment]
@lsmith130 thanks for the gentle reminder.  The latest version should work for modules in most cases. Feel free to file another issue if you find things that aren't working.
