### ISSUE TITLE
cant find definition

### ISSUE THREAD

**Issue by Kurt-Shiwz** [zmb3/gogetdoc#37]
if import some lib like ". github.com/a/b", can't goto definition which define in b.
function is also undefined.
```
// b.go
type GlobalConfig struct {
	Localaddr string
}
func InitGlobalVars(globalconfig *GlobalConfig) error {
}


// main.go
import (
. github.com/a/b
)
// can't goto definition
globalconfig := &GlobalConfig{}
// InitGlobalVars is undefined
InitGlobalVars(globalconfig)
```

**Comment by Kurt-Shiwz** [comment]
// src/a/b/b.go
package b

type GlobalConfig struct {
	Localaddr string
}

func InitGlobalVars(globalconfig *GlobalConfig) error {
	globalconfig.Localaddr = "ss"
	return nil
}


// src/a/main.go
package main

import (
	"fmt"
	// "rr/b"
	. "rr/b"
)

func main() {
	// t := b.GlobalConfig{Localaddr: "a"}
	t := GlobalConfig{Localaddr: "a"}
	fmt.Printf("%v\n", t)
	// b.InitGlobalVars(&t)
	InitGlobalVars(&t)
	fmt.Printf("%v\n", t)
}

@zmb3

**Comment by zmb3** [comment]
Seems to work fine for me.  Is your GOPATH set properly?

```
~/src/rr
➜ ls
b       main.go

~/src/rr
➜ cat main.go
package main

import (
	"fmt"
	//	"rr/b"
	. "rr/b"
)

func main() {
	t := GlobalConfig{Localaddr: "a"}
	fmt.Printf("%v\n", t)
	InitGlobalVars(&t)
	fmt.Printf("%v\n", t)
}

~/src/rr
➜ cat b/b.go
package b

type GlobalConfig struct {
	Localaddr string
}

func InitGlobalVars(globalconfig *GlobalConfig) error {
	globalconfig.Localaddr = "ss"
	return nil
}

~/src/rr
➜ gogetdoc -pos "main.go:#132" -json | jq .
{
  "name": "InitGlobalVars",
  "import": "rr/b",
  "pkg": "b",
  "decl": "func InitGlobalVars(globalconfig *GlobalConfig) error",
  "doc": "",
  "pos": "/Users/zbergquist/src/rr/b/b.go:7:6"
}
```

**Comment by Kurt-Shiwz** [comment]
i use gogetdoc with vscode
    "go.goroot": "/usr/local/opt/go@1.9/libexec",
    "go.toolsGopath": "/Users/shiweize/project/gocode/tools",
    "go.useLanguageServer": true,
    "go.toolsGopath": "/Users/kurt/project/gocode/tools",
    "files.autoSave": "off",
    "go.lintOnSave": "off",
    "go.inferGopath": true,
    "go.gopath": "/Users/kurt/project/gocode",
    "go.docsTool": "gogetdoc",

i found set  "go.useLanguageServer" to false and it  work. ^_^

**Comment by Kurt-Shiwz** [comment]
i find gogetdoc is slower than godef, but godef does not understand about "." imports
