### ISSUE TITLE
Allow passing in of file content

### ISSUE THREAD

**Issue by mjibson** [zmb3/gogetdoc#4]
Editor files often aren't yet saved to disk, so the files read will be wrong WRT the editor. guru (formerly oracle) has the option. Using its same input format would be great (I maintain an editor plugin and not having to support another file format would be awesome.)

**Comment by dominikh** [comment]
guru's format in particular has the advantage that multiple files can be passed at once. That way, if multiple files of a package are unsaved, one will still get the correct result. And it's fairly simple to support.

**Comment by zmb3** [comment]
Sounds like a great idea. I was curious how well we could make it work if there are multiple unsaved files, so I'm glad to hear guru handles this all.

I'lll have some time to take a look this weekend.
