### ISSUE TITLE
gogetdoc doesn't work with the -modified flag after the latest commit

### ISSUE THREAD

**Issue by ramya-rao-a** [zmb3/gogetdoc#41]
As of 
https://github.com/zmb3/gogetdoc/commit/ba76b40238cbfb0995551775ef2895e9c7437c2a, gogetdoc doesn't work with the -modified flag

I am using `gogetdoc` in VS Code which uses the `-modified` flag by default.
It works as expected when I changed the VS Code extension to not use the `-modified` flag

cc @zmb3

**Comment by dominikh** [comment]
Such is the life of `go/packages`.
