### ISSUE TITLE
Getting documentation for interface method returns full path to type

### ISSUE THREAD

**Issue by SteelPhase** [zmb3/gogetdoc#44]
I've run into this a few times, and I've finally dug into what I'm seeing. I'm not sure what is causing it, or if it's actually expected. When you request the documentation for an interface method the type names display as the full path to the type instead of what appears to be the standard format of `package.type` or `type` that appears in the rest of the displayed documentation. Is there any way to get gogetdoc to print the more human readable version of the type when grabbing the documentation for a interface method?

I've created a simple go file that has the behavior I'm experiencing
```golang
package rabbit

// Thing is an interface
type Thing interface {

	// Do does a thing
	Do(s Stuff) Stuff
}

// Stuff is a struct
type Stuff struct{}

// ThingImplemented matches Thing interface
type ThingImplemented struct{}

// Do does stuff
func (ti *ThingImplemented) Do(s Stuff) Stuff {
	return s
}
```

When executing gogetdoc against the interface Do method I receive this out put
```bash
SteelPhase@mac:rabbit$gogetdoc -pos example.go:#86 -json | jq
{
  "name": "Do",
  "import": "github.com/SteelPhase/rabbit",
  "pkg": "rabbit",
  "decl": "func (github.com/SteelPhase/rabbit.Thing).Do(s github.com/SteelPhase/rabbit.Stuff) github.com/SteelPhase/rabbit.Stuff",
  "doc": "Do does a thing\n",
  "pos": "/Users/SteelPhase/Code/Go/src/github.com/SteelPhase/rabbit/example.go:7:2"
}
```

I was expecting to see
```bash
SteelPhase@mac:rabbit$gogetdoc -pos example.go:#86 -json | jq
{
  "name": "Do",
  "import": "github.com/SteelPhase/rabbit",
  "pkg": "rabbit",
  "decl": "func (Thing).Do(s Stuff) Stuff",
  "doc": "Do does a thing\n",
  "pos": "/Users/SteelPhase/Code/Go/src/github.com/SteelPhase/rabbit/example.go:7:2"
}
```

As an addition example, when you request the documentation for ThingImplemented's Do method you get this
```bash
SteelPhase@mac:rabbit$gogetdoc -pos example.go:#270 -json | jq
{
  "name": "Do",
  "import": "github.com/SteelPhase/rabbit",
  "pkg": "rabbit",
  "decl": "func (ti *ThingImplemented) Do(s Stuff) Stuff",
  "doc": "Do does stuff\n",
  "pos": "/Users/SteelPhase/Code/Go/src/github.com/SteelPhase/rabbit/example.go:17:29"
}

**Comment by SteelPhase** [comment]
It appears this is already documented in the code for gogetdoc, but no issue existed for it that I could find.

```golang
// Not supported by go/printer

// TODO(dominikh): Methods in interfaces are syntactically
// represented as fields. Using types.Object.String for those
// causes them to look different from real functions.
// go/printer doesn't include the import paths in names, while
// Object.String does. Fix that.
```

**Comment by zmb3** [comment]
@SteelPhase do you mind giving the cod in #45 a try and letting me know how that works for you?

**Comment by SteelPhase** [comment]
#45 does solve this problem for me. I ran a `go install` and verified it looks correct in vscode as well.
