### ISSUE TITLE
go get failing on gogetdoc

### ISSUE THREAD

**Issue by ramya-rao-a** [zmb3/gogetdoc#46]
Run `go get -u github.com/zmb3/gogetdoc` to get the error

.../github.com/zmb3/gogetdoc/vendor/golang.org/x/tools/go/packages/packages.go:695: undefined: types.SizesFor

cc @zmb3

**Comment by eoconnor** [comment]
Seeing the same thing.

**Comment by zmb3** [comment]
I can't reproduce:
```
➜ mkdir foo

➜ cd foo

➜ export GOPATH=$(pwd)

➜ GO111MODULE=off go get github.com/zmb3/gogetdoc
```

**Comment by ramya-rao-a** [comment]
In my case, it was for Go 1.8
Sorry for not specifying it earlier.

**Comment by zmb3** [comment]
Ah, I'm probably OK with that.  I think `go/packages` only supports the last 2 versions of Go, and so by depending on that I'm in the same boat here.

Why such an old Go version?

**Comment by ramya-rao-a** [comment]
Because VS Code still supports Go 1.8 :)

I am ok closing this issue. I can update the Go extension to not provide `gogetdoc` as an option for Go 1.8 and lower

**Comment by zmb3** [comment]
That seems like a reasonable approach.

If it becomes prohibitive we can think about publishing binaries such that you can install `gogetdoc` for users without running `go get`.  I _think_ this would still work but I'm not entirely sure with the new dependency on `go list`.
